import json
from pathlib import Path

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# LiH/STO-3G bond-stretching VQE energy curve (frozen core)\n",
                "\n",
                "Goal: repeat the Phase 4 bond-stretching workflow (notebook 02) on\n",
                "LiH instead of H2, using a frozen-core active space, to see whether\n",
                "UCCSD stops being exact once the active space has more than one\n",
                "occupied/virtual orbital pair.\n",
                "\n",
                "Pipeline, repeated at each bond distance:\n",
                "\n",
                "1. Define molecular geometry and basis at a given Li-H distance.\n",
                "2. Use PySCF through Qiskit Nature to obtain the electronic-structure problem.\n",
                "3. Freeze the Li 1s core orbital (FreezeCoreTransformer).\n",
                "4. Build the second-quantized fermionic Hamiltonian over the active space.\n",
                "5. Map the fermionic Hamiltonian to qubits using Jordan-Wigner.\n",
                "6. Build a Hartree-Fock initial state and UCCSD ansatz over the active space.\n",
                "7. Run VQE with a classical optimizer (noiseless statevector simulation, SciPy SLSQP).\n",
                "8. Compare against an exact classical eigensolver reference (in the same active space)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import importlib.metadata as metadata\n",
                "\n",
                "packages = [\n",
                "    'qiskit',\n",
                "    'qiskit-nature',\n",
                "    'qiskit-algorithms',\n",
                "    'pyscf',\n",
                "    'numpy',\n",
                "    'scipy',\n",
                "    'matplotlib',\n",
                "    'pandas',\n",
                "]\n",
                "\n",
                "for package in packages:\n",
                "    try:\n",
                "        print(f'{package}: {metadata.version(package)}')\n",
                "    except metadata.PackageNotFoundError:\n",
                "        print(f'{package}: NOT INSTALLED')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Active space, before the bond-distance sweep\n",
                "\n",
                "LiH/STO-3G has 6 spatial orbitals (Li 1s, 2s, 2px, 2py, 2pz; H 1s) and\n",
                "4 electrons. Freezing the Li 1s core removes 1 spatial orbital and 2\n",
                "electrons, leaving an active space of 5 spatial orbitals and 2\n",
                "electrons (1 alpha, 1 beta). We check this once at the experimental\n",
                "equilibrium distance (1.5949 A) before running the full grid."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "from qiskit_nature.second_q.drivers import PySCFDriver\n",
                "from qiskit_nature.units import DistanceUnit\n",
                "from qiskit_nature.second_q.transformers import FreezeCoreTransformer\n",
                "\n",
                "_check_driver = PySCFDriver(\n",
                "    atom='Li 0 0 0; H 0 0 1.5949',\n",
                "    unit=DistanceUnit.ANGSTROM,\n",
                "    charge=0,\n",
                "    spin=0,\n",
                "    basis='sto3g',\n",
                ")\n",
                "_full_problem = _check_driver.run()\n",
                "print(f'Full space: {_full_problem.num_spatial_orbitals} spatial orbitals, '\n",
                "      f'{_full_problem.num_particles} particles (alpha, beta)')\n",
                "\n",
                "_freeze_core_transformer = FreezeCoreTransformer(freeze_core=True)\n",
                "_active_problem = _freeze_core_transformer.transform(_full_problem)\n",
                "print(f'Frozen-core active space: {_active_problem.num_spatial_orbitals} spatial orbitals, '\n",
                "      f'{_active_problem.num_particles} particles (alpha, beta)')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Bond-distance grid\n",
                "\n",
                "We sweep the Li-H distance from compressed, through the experimental\n",
                "equilibrium (1.5949 A), to strongly stretched (6.0 A)."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "bond_lengths_angstrom = [\n",
                "    1.0, 1.2, 1.4, 1.5949, 1.8, 2.1, 2.5, 3.0, 3.5, 4.5, 6.0,\n",
                "]\n",
                "basis = 'sto3g'\n",
                "\n",
                "print(f'Number of bond distances: {len(bond_lengths_angstrom)}')\n",
                "print(f'Range: {min(bond_lengths_angstrom)} A to {max(bond_lengths_angstrom)} A')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. Helper function: one bond distance, full pipeline\n",
                "\n",
                "Same structure as notebook 02's helper, with one addition: the\n",
                "fermionic Hamiltonian is built after applying `FreezeCoreTransformer`,\n",
                "so every downstream quantity (spin orbitals, qubits, Pauli terms,\n",
                "ansatz) reflects the active space, not the full LiH/STO-3G space."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import numpy as np\n",
                "from scipy.optimize import minimize\n",
                "\n",
                "from qiskit import transpile\n",
                "from qiskit.quantum_info import Statevector\n",
                "from qiskit_nature.second_q.mappers import JordanWignerMapper\n",
                "from qiskit_nature.second_q.circuit.library import HartreeFock, UCCSD\n",
                "\n",
                "\n",
                "def run_lih_sto3g_point(bond_length_angstrom, basis='sto3g'):\n",
                "    \"\"\"Run the frozen-core LiH/STO-3G VQE pipeline at a single Li-H bond distance.\"\"\"\n",
                "    driver = PySCFDriver(\n",
                "        atom=f'Li 0 0 0; H 0 0 {bond_length_angstrom}',\n",
                "        unit=DistanceUnit.ANGSTROM,\n",
                "        charge=0,\n",
                "        spin=0,\n",
                "        basis=basis,\n",
                "    )\n",
                "    full_problem = driver.run()\n",
                "\n",
                "    freeze_core_transformer = FreezeCoreTransformer(freeze_core=True)\n",
                "    problem = freeze_core_transformer.transform(full_problem)\n",
                "\n",
                "    fermionic_op = problem.hamiltonian.second_q_op()\n",
                "\n",
                "    mapper = JordanWignerMapper()\n",
                "    qubit_op = mapper.map(fermionic_op)\n",
                "\n",
                "    # Exact classical reference within the active space, possible here because\n",
                "    # the frozen-core active space is still small enough (10 qubits) to diagonalize.\n",
                "    hamiltonian_matrix = qubit_op.to_matrix()\n",
                "    electronic_eigenvalues = np.linalg.eigvalsh(hamiltonian_matrix)\n",
                "    exact_electronic_energy = float(np.min(electronic_eigenvalues).real)\n",
                "    exact_energy = exact_electronic_energy + float(problem.nuclear_repulsion_energy)\n",
                "\n",
                "    initial_state = HartreeFock(\n",
                "        num_spatial_orbitals=problem.num_spatial_orbitals,\n",
                "        num_particles=problem.num_particles,\n",
                "        qubit_mapper=mapper,\n",
                "    )\n",
                "    ansatz = UCCSD(\n",
                "        num_spatial_orbitals=problem.num_spatial_orbitals,\n",
                "        num_particles=problem.num_particles,\n",
                "        qubit_mapper=mapper,\n",
                "        initial_state=initial_state,\n",
                "    )\n",
                "\n",
                "    history = []\n",
                "\n",
                "    def energy_from_parameters(parameters):\n",
                "        bound_circuit = ansatz.assign_parameters(parameters, inplace=False)\n",
                "        # Statevector.from_instruction is exact either way, but on the raw\n",
                "        # ansatz (opaque multi-qubit excitation gates) it goes through a\n",
                "        # generic sparse matrix-exponential path that measured at ~17s per\n",
                "        # call for this 24-parameter/10-qubit ansatz. Transpiling to a plain\n",
                "        # gate basis first lets Statevector apply gates directly instead,\n",
                "        # cutting this to ~0.3s per call (~50x) with no change in the result.\n",
                "        transpiled_circuit = transpile(\n",
                "            bound_circuit, basis_gates=['u3', 'cx'], optimization_level=1,\n",
                "        )\n",
                "        state = Statevector.from_instruction(transpiled_circuit)\n",
                "        electronic_energy = np.real(state.expectation_value(qubit_op))\n",
                "        total_energy = electronic_energy + float(problem.nuclear_repulsion_energy)\n",
                "        history.append(float(total_energy))\n",
                "        return float(total_energy)\n",
                "\n",
                "    initial_point = np.zeros(ansatz.num_parameters)\n",
                "\n",
                "    opt_result = minimize(\n",
                "        energy_from_parameters,\n",
                "        initial_point,\n",
                "        method='SLSQP',\n",
                "        options={'maxiter': 1000, 'ftol': 1e-10},\n",
                "    )\n",
                "\n",
                "    vqe_energy = float(opt_result.fun)\n",
                "    abs_error = abs(vqe_energy - exact_energy)\n",
                "\n",
                "    return {\n",
                "        'bond_length_angstrom': bond_length_angstrom,\n",
                "        'active_spatial_orbitals': problem.num_spatial_orbitals,\n",
                "        'active_electrons': sum(problem.num_particles),\n",
                "        'spin_orbitals': 2 * problem.num_spatial_orbitals,\n",
                "        'qubits': qubit_op.num_qubits,\n",
                "        'pauli_terms': len(qubit_op),\n",
                "        'ansatz_parameters': ansatz.num_parameters,\n",
                "        'exact_energy_hartree': exact_energy,\n",
                "        'vqe_energy_hartree': vqe_energy,\n",
                "        'abs_error_hartree': abs_error,\n",
                "        'optimizer_success': bool(opt_result.success),\n",
                "        'optimizer_message': str(opt_result.message),\n",
                "        'num_function_evaluations': len(history),\n",
                "    }\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Look at the ansatz once, at equilibrium\n",
                "\n",
                "Unlike H2/STO-3G, the frozen-core LiH active space has 5 spatial\n",
                "orbitals (1 occupied, 4 virtual) instead of 1-occupied/1-virtual, so\n",
                "UCCSD has many more singles and doubles excitations to draw on here."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "_driver = PySCFDriver(\n",
                "    atom='Li 0 0 0; H 0 0 1.5949',\n",
                "    unit=DistanceUnit.ANGSTROM,\n",
                "    charge=0,\n",
                "    spin=0,\n",
                "    basis=basis,\n",
                ")\n",
                "_problem = _freeze_core_transformer.transform(_driver.run())\n",
                "_mapper = JordanWignerMapper()\n",
                "\n",
                "_initial_state = HartreeFock(\n",
                "    num_spatial_orbitals=_problem.num_spatial_orbitals,\n",
                "    num_particles=_problem.num_particles,\n",
                "    qubit_mapper=_mapper,\n",
                ")\n",
                "_ansatz = UCCSD(\n",
                "    num_spatial_orbitals=_problem.num_spatial_orbitals,\n",
                "    num_particles=_problem.num_particles,\n",
                "    qubit_mapper=_mapper,\n",
                "    initial_state=_initial_state,\n",
                ")\n",
                "\n",
                "print(f'Ansatz: {_ansatz.__class__.__name__}')\n",
                "print(f'Number of qubits in ansatz: {_ansatz.num_qubits}')\n",
                "print(f'Number of variational parameters: {_ansatz.num_parameters}')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Run the energy curve\n",
                "\n",
                "Now we repeat the full pipeline at every bond distance in the grid and\n",
                "collect the results into a table."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "\n",
                "results = []\n",
                "for bond_length_angstrom in bond_lengths_angstrom:\n",
                "    print(f'Running bond distance {bond_length_angstrom} A ...')\n",
                "    point_result = run_lih_sto3g_point(bond_length_angstrom, basis=basis)\n",
                "    results.append(point_result)\n",
                "\n",
                "results_df = pd.DataFrame(results)\n",
                "print()\n",
                "print(f'Completed {len(results_df)} bond distances.')\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 6. Results table\n",
                "\n",
                "A compact view of the key quantities at every bond distance."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "display_columns = [\n",
                "    'bond_length_angstrom',\n",
                "    'active_spatial_orbitals',\n",
                "    'active_electrons',\n",
                "    'qubits',\n",
                "    'pauli_terms',\n",
                "    'ansatz_parameters',\n",
                "    'exact_energy_hartree',\n",
                "    'vqe_energy_hartree',\n",
                "    'abs_error_hartree',\n",
                "    'optimizer_success',\n",
                "    'num_function_evaluations',\n",
                "]\n",
                "\n",
                "with pd.option_context('display.float_format', lambda v: f'{v:.10f}'):\n",
                "    print(results_df[display_columns].to_string(index=False))\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 7. Plot: energy curve and VQE error\n",
                "\n",
                "Top panel: exact diagonalization energy and VQE energy versus Li-H\n",
                "bond distance. Bottom panel: absolute VQE error versus bond distance,\n",
                "on a log scale."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import matplotlib.pyplot as plt\n",
                "from pathlib import Path\n",
                "\n",
                "fig, (ax_energy, ax_error) = plt.subplots(2, 1, figsize=(8, 9), sharex=True)\n",
                "\n",
                "ax_energy.plot(\n",
                "    results_df['bond_length_angstrom'],\n",
                "    results_df['exact_energy_hartree'],\n",
                "    'o-', label='Exact diagonalization (active space)',\n",
                ")\n",
                "ax_energy.plot(\n",
                "    results_df['bond_length_angstrom'],\n",
                "    results_df['vqe_energy_hartree'],\n",
                "    'x--', label='VQE (UCCSD)',\n",
                ")\n",
                "ax_energy.set_ylabel('Total energy (Hartree)')\n",
                "ax_energy.set_title('LiH/STO-3G energy curve, frozen core: exact vs VQE')\n",
                "ax_energy.legend()\n",
                "ax_energy.grid(True, alpha=0.3)\n",
                "\n",
                "ax_error.semilogy(\n",
                "    results_df['bond_length_angstrom'],\n",
                "    results_df['abs_error_hartree'],\n",
                "    's-', color='tab:red',\n",
                ")\n",
                "ax_error.set_xlabel('Li-H bond distance (Angstrom)')\n",
                "ax_error.set_ylabel('|VQE - exact| (Hartree)')\n",
                "ax_error.set_title('Absolute VQE error vs bond distance')\n",
                "ax_error.grid(True, alpha=0.3, which='both')\n",
                "\n",
                "fig.tight_layout()\n",
                "\n",
                "# Notebook kernels default to the notebook's own directory as cwd,\n",
                "# so the repo-root figures/ directory is one level up.\n",
                "figure_path = Path('..') / 'figures' / 'lih_energy_curve_frozen_core.png'\n",
                "figure_path.parent.mkdir(parents=True, exist_ok=True)\n",
                "fig.savefig(figure_path, dpi=150)\n",
                "print(f'Saved figure to {figure_path}')\n",
                "\n",
                "plt.show()\n"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 8. Scientific interpretation\n",
                "\n",
                "- Freezing the Li 1s core reduces LiH/STO-3G from 4 electrons in 6\n",
                "  spatial orbitals down to an active space of **2 electrons in 5\n",
                "  spatial orbitals** (1 occupied, 4 virtual).\n",
                "- This is a genuinely different orbital structure than H2/STO-3G (1\n",
                "  occupied, 1 virtual): UCCSD now has many more possible single and\n",
                "  double excitations to draw on, reflected in the much larger\n",
                "  parameter count of the ansatz built above.\n",
                "- However: with only 2 active electrons, singles and doubles are the\n",
                "  *only* excitations that exist. A determinant can't be triply or\n",
                "  quadruply excited if there are only 2 electrons to redistribute. So\n",
                "  CISD (classically) and UCCSD (here) are still mathematically\n",
                "  equivalent to full CI in this active space, for the same structural\n",
                "  reason as H2 (no excitation levels beyond doubles exist to be\n",
                "  missing) even though the orbital count grew.\n",
                "- If the results table above shows `abs_error_hartree` at\n",
                "  floating-point round-off across the whole curve (as it did for\n",
                "  H2/STO-3G), that is the expected outcome given the above, not a\n",
                "  surprise or a bug: freezing the core all the way down to 2 active\n",
                "  electrons removes the thing (3+ active electrons) needed for UCCSD\n",
                "  to become a genuine truncated approximation.\n",
                "- This directly answers the open question carried over from\n",
                "  `notes/uccsd_classical_vs_quantum.md`: yes, freezing the core on LiH\n",
                "  can make UCCSD exact for the wrong reason (too few active electrons),\n",
                "  independent of how many virtual orbitals are in the active space.\n",
                "- To actually see UCCSD deviate from full CI, the active space needs\n",
                "  at least 3-4 active electrons, e.g. LiH without freezing the core, or\n",
                "  a molecule/basis where the frozen-core active space still leaves 4+\n",
                "  electrons active."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Limitations\n",
                "\n",
                "1. This is an ideal statevector simulation, not a hardware calculation.\n",
                "2. No sampling noise, device noise, decoherence, or transpilation constraints are included.\n",
                "3. Exact diagonalization is only possible here because the frozen-core active space is small (10 qubits, 1024x1024 matrix).\n",
                "4. Jordan-Wigner is used throughout; no qubit-reduction mapping or symmetry tapering is applied.\n",
                "5. The frozen-core approximation itself is not validated against the non-frozen 4-electron result in this notebook (see next step).\n",
                "6. The optimizer is restarted from the same all-zero initial point at each bond distance; no warm-starting from a neighboring point.\n",
                "7. As argued above, this active space (2 active electrons) is not expected to be a genuine test of UCCSD truncation error; a follow-up notebook without core freezing (4 active electrons) is needed for that."
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "pygments_lexer": "ipython3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

path = Path("notebooks/03_lih_energy_curve_frozen_core.ipynb")
path.parent.mkdir(parents=True, exist_ok=True)
path.write_text(json.dumps(notebook, indent=2), encoding="utf-8")

print(f"Wrote {path}")
